export const fakeTransactions = [
  {
    _id: "1",
    date: "21.01.20",
    type: "income",
    category: "car",
    comment: "blanty",
    sum: "1000",
    color: "#FF5733",
  },
  {
    _id: "2",
    date: "21.01.20",
    type: "expense",
    category: "Car",
    comment: "paliwo",
    sum: "1000",
    color: "#33FF57",
  },
  {
    _id: "3",
    date: "21.01.20",
    type: "expense",
    category: "Household products",
    comment: "Zakupy w Lidlu w sobotę",
    sum: "21100",
    color: "#5733FF",
  },
  {
    _id: "4",
    date: "21.01.20",
    type: "income",
    category: "Other expenses",
    comment: "paliwo",
    sum: "1000",
    color: "#FF33E6",
  },
  {
    _id: "5",
    date: "21.01.20",
    type: "income",
    category: "car",
    comment: "meta",
    sum: "10000",
    color: "#33FFEC",
  },
  {
    _id: "6",
    date: "21.01.20",
    type: "expense",
    category: "car",
    comment: "paliwo",
    sum: "1000",
    color: "#FFD700",
  },
  {
    _id: "7",
    date: "21.01.20",
    type: "income",
    category: "car",
    comment: "wóda",
    sum: "100",
    color: "#8B4513",
  },
  {
    _id: "8",
    date: "21.01.20",
    type: "expense",
    category: "car",
    comment: "paliwo",
    sum: "100",
    color: "#8FBC8F",
  },
  {
    _id: "9",
    date: "21.01.20",
    type: "income",
    category: "car",
    comment: "paliwo",
    sum: "1000",
    color: "#4B0082",
  },
  {
    _id: "10",
    date: "21.01.20",
    type: "income",
    category: "Entertainment",
    comment: "Tickets",
    sum: "500",
    color: "#FF1493",
  },
  {
    _id: "11",
    date: "21.01.20",
    type: "expense",
    category: "Groceries",
    comment: "Weekly shopping",
    sum: "200",
    color: "#008080",
  },
  {
    _id: "12",
    date: "21.01.20",
    type: "income",
    category: "Health",
    comment: "Gym membership",
    sum: "300",
    color: "#ADFF2F",
  },
  {
    _id: "13",
    date: "21.01.20",
    type: "expense",
    category: "Electronics",
    comment: "New phone",
    sum: "700",
    color: "#FF4500",
  },
  {
    _id: "14",
    date: "21.01.20",
    type: "income",
    category: "Travel",
    comment: "Flight tickets",
    sum: "1000",
    color: "#1E90FF",
  },
  {
    _id: "15",
    date: "21.01.20",
    type: "expense",
    category: "Dining",
    comment: "Dinner",
    sum: "50",
    color: "#FFA500",
  },
  {
    _id: "16",
    date: "21.01.20",
    type: "income",
    category: "Education",
    comment: "Books",
    sum: "150",
    color: "#9370DB",
  },
  {
    _id: "17",
    date: "21.01.20",
    type: "expense",
    category: "Utilities",
    comment: "Electricity bill",
    sum: "120",
    color: "#32CD32",
  },
  {
    _id: "18",
    date: "21.01.20",
    type: "income",
    category: "Gifts",
    comment: "Birthday gift",
    sum: "200",
    color: "#FF4500",
  },
  {
    _id: "19",
    date: "21.01.20",
    type: "expense",
    category: "Clothing",
    comment: "New shoes",
    sum: "80",
    color: "#FFD700",
  },
  {
    _id: "20",
    date: "21.01.20",
    type: "income",
    category: "Savings",
    comment: "Deposit",
    sum: "300",
    color: "#87CEEB",
  },
];
