export const fakeTransactions = [
  {
    _id: "1",
    date: "21.01.20",
    type: "income",
    category: "car",
    comment: "blanty",
    sum: "1000",
  },
  {
    _id: "2",
    date: "21.01.20",
    type: "expense",
    category: "Car",
    comment: "paliwo",
    sum: "1000",
  },
  {
    _id: "3",
    date: "21.01.20",
    type: "expense",
    category: "Household products",
    comment: "Zakupy w Lidlu w sobotę",
    sum: "21100",
  },
  {
    _id: "4",
    date: "21.01.20",
    type: "income",
    category: "Other expenses",
    comment: "paliwo",
    sum: "1000",
  },
  {
    _id: "5",
    date: "21.01.20",
    type: "income",
    category: "car",
    comment: "meta",
    sum: "10000",
  },
  // {
  //   _id: "6",
  //   date: "21.01.20",
  //   type: "expense",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "7",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "wóda",
  //   sum: "100",
  // },
  // {
  //   _id: "8",
  //   date: "21.01.20",
  //   type: "expense",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "100",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
  // {
  //   _id: "9",
  //   date: "21.01.20",
  //   type: "income",
  //   category: "car",
  //   comment: "paliwo",
  //   sum: "1000",
  // },
];
